### ISSUE TITLE
If putting phone to sleep then wake up causes the layout to break 

### ISSUE THREAD

**Issue by helloniklas** [HarshilShah/DeckTransition#33] opened 2017-08-31 09:28 UTC
If the modal view is shown with the little black border at the top, put the phone to sleep (i.e screen off to black) then press home button to wake again. When it now comes back the modal screen is drawn in full screen without the black top bits.

**Comment by HarshilShah** [comment] 2017-08-31 10:53
I can't reproduce this with the latest version of the demo app. Could you verify that this error occurs on the latest release (1.0.2), and either upload a demo app or post more detailed reproduction steps?

A similar error was discovered in #15, fixed in #21, and released in v0.4

**Comment by helloniklas** [comment] 2017-08-31 11:01
Hm right, running your demo app it works fine... So must be something with my view hierarchy in my other app that causes the issue... I'm using Storyboards with custom DeckTransition segues, wonder if that affects it?

**Comment by helloniklas** [comment] 2017-08-31 11:03
Tried with a segue in your example app and it works fine as well...  will do some more tests on my app to see why it's happening there... thanks.

**Comment by HarshilShah** [comment] 2017-08-31 13:56
One guess on my part: Are you presenting some VC on entering/leaving background? One common use case is to present either a password VC or some other random view to obscure content in the app switcher. This was also brought up in #4, and the gist of it is that `UIPresentationController` kinda seems to break when another VC is presented with a fullscreen style

**Comment by helloniklas** [comment] 2017-08-31 13:58
Not really... I thought it had to do with my specific nesting, ie. tab bar inside navigation controllers inside navigation controller...  but replicating my view controller hierarchy in your example and the example still works... can't seem to replicate the problem at all in the example, but it's happening in my app with the latest version... will let you know if I find out why...

**Comment by HarshilShah** [comment] 2017-09-01 07:22
Cool, let me know if you find anything. Closing this issue for now.

**Closed by HarshilShah** 2017-09-01 07:22 UTC
