### ISSUE TITLE
Dragging past threshold closes view even if finger does not let go.

### ISSUE THREAD

**Issue by benguild** [HarshilShah/DeckTransition#50] opened 2017-11-12 10:04 UTC
I noticed that if you drag the view past the threshold to dismiss it, you can't drag your finger back if you don't let go to cancel it.

It's a bit frustrating if you drag it down to "peek" underneath, and then it closes. Just running some tests here to examine the functionality and noticed this.

**Comment by HarshilShah** [comment] 2017-11-12 10:35
Not quite sure what you mean by:

> you can't drag your finger back if you don't let go to cancel it.

**Comment by benguild** [comment] 2017-11-12 10:36
Basically, if I drag my finger to the bottom of the screen... I can’t drag
it to the top of the screen to restore the view without letting go. It
always dismisses.
-- 
iPhoneから送信

**Comment by HarshilShah** [comment] 2017-11-12 10:48
Dragging beyond a limit to dismiss the view is by design. I prefer it to having to guess whether or not the view will dismiss or stay based on how much you have dragged when you let go. Needing a new touch to do anything after VC presentation/dismissal is just standard iOS behaviour.

**Comment by benguild** [comment] 2017-11-12 10:51
I guess so, but the difference is that in the music app you're minimizing something where as with this you're most likely closing it and it's more work for the user to recreate that concept.

Similar to how buttons on OSes let you drag off of them before letting go of the mouse/tap in case you change your mind, I think it'd be nice to have the option to pull the view back over the threshold to undo the cancel if you haven't let go of your finger yet? Just my thoughts... feels natural to me if I haven't let go of the view to have it stay as I drag it.

**Comment by HarshilShah** [comment] 2017-11-12 10:58
Dunno about the "more work" bit; sure it's minimising vs. closing, but you probably clicked a button in the previous screen to get there, and can do so again after the dismissal.

I don't mind the idea of an interactive transition, but it's going to be difficult to map the user's expectations for what's going to happen if they let go at a particular distance or with a particular speed. This isn't a standard transition across iOS, it's used in just a couple of apps, so there's not much muscle memory like with say the interactive animations for `UINavigationController`, etc.

**Comment by benguild** [comment] 2017-11-12 11:00
I mean to me the biggest issue is that if I drag the view far enough it dismisses, even if I'm barely moving it at all. That feels totally unnatural at such a low velocity to have it suddenly jump to a high velocity and dismiss. Clearly not what I'd want if I was doing that.

**Comment by HarshilShah** [comment] 2017-11-12 11:05
Sure, that's also how the Music app's transition works. I just don't think "peeking" is a common enough use case to support

**Comment by benguild** [comment] 2017-11-12 11:11
Understandable. I believe this may have been changed in iOS 11.2 due to user feedback/radars.

**Comment by HarshilShah** [comment] 2017-11-12 11:14
Yup, noticed that. And not a fan of how it works. I have some ideas about how to better communicate whether it's going to dismiss at a particular point, maybe an interactive dismissal can happen if that works out

**Closed by HarshilShah** 2017-11-12 11:14 UTC
