### ISSUE TITLE
In-Call Status Bar Issue

### ISSUE THREAD

**Issue by hamedh** [HarshilShah/DeckTransition#15] opened 2017-06-16 01:28 UTC
It seems there's two issues when there's an in-call status bar with a taller height. First, the status bar covers up the presented view controller's top part.

Second, after dismissing the presented modal, the presented view controller isn't being reset correctly. To reproduce, on the demo toggle in-call status bar, present the modal, take the app to background and bring it back. Now the presented view controller's frame is wrong. It's something to do with the transform, but I haven't figured it out yet.. On my own app, the controller's frame is actually going off screen (e.g. too large) after the modal is dismissed

**Comment by gcox** [comment] 2017-07-02 16:47
@hamedh There are a mountain of problems caused by the in-call status bar. This seems to be a general problem experience by anyone implementing a custom VC presentation and I've yet to find any general solution that fixes all the problems...yet, somehow, Apple's apps don't suffer from these problems.

I actually don't see the problem you describe as written. For me, when I follow your repro steps, it is the *presenting* controller's view that is not placed correctly, maybe that's what you meant.

It may help get this fixed if we clearly list the problems, here are the ones I've seen so far:

### Problem 1
* Launch app
* Present modal
* Enable in-call status bar (**presented** VC's view isn't shifted down)
* Disable in-call status bar
* **presenting** view controller's view is now too large

### Problem 2
* Launch app
* Enable in-call status bar
* Present Modal
* Dismiss in-call status bar
* **presenting** VC's view isn't shifted up
---
#### *For problems 3 & 4*:
* Add a navigation controller to `Main.storyboard`
* Make the nav controller the initial VC
* Make the old initial VC the nav controller's root VC
* Add some bar button items so things will be easier to see

### Problem 3
* Launch app
* Present modal
* Enable in-call status bar
* modal is covered by the status bar

<img width="487" alt="screenshot 2017-07-02 12 39 38" src="https://user-images.githubusercontent.com/251512/27771800-8d682e8e-5f23-11e7-937f-dfcd9242da8e.png">


### Problem 4 (continued from problem 3)
* Launch app
* Present modal
* Enable in-call status bar
* Dismiss the in-call status bar
* Dismiss the modal
* **presenting** view controller's view is shifted up and the nav bar is now under the status bar

<img width="487" alt="screenshot 2017-07-02 12 38 30" src="https://user-images.githubusercontent.com/251512/27771791-6172d900-5f23-11e7-980e-79e6e4bbee38.png">

**Comment by HarshilShah** [comment] 2017-07-03 04:41
Hi there folks,

Sorry for the delayed response. I’ve been working on this for a while and getting, um, not that far.

Thanks a lot for the test cases, those help a lot. I’ve mostly figured out how to solve the issue with having view controllers resize when the status bar is presented (pushing a branch for that soon), but I’ve gotten nowhere on the issue of the presenting view controller resizing on resuming from background. I’ve come across this bug in Apple’s own implementation many times, so I’m not sure if its fixable at all.

Posting the code ASAP, will add a link here when I do. Do take a look and let me know if it works, and if you’ve found any solutions to the issue with backgrounding

**Comment by HarshilShah** [comment] 2017-07-03 10:25
Alright, so here it is: https://github.com/HarshilShah/DeckTransition/tree/status-bar

The issues with the presenting view have been fixed. Two issues remain:

1. When the modal is presented while the double-height status bar is visible, and then the status bar returns to normal height, the presented view for some reason leaves a 20px gap below even while reporting the full size for `frame` and `branch`.

2. The presenting view animation when the status bar changes height is extremely janky.

If either of you have the time/know how to fix this, I would appreciate the help. Thanks!

**Comment by gcox** [comment] 2017-07-03 12:12
@HarshilShah Thanks for fixing this!

This commit fixes the 20px gap at the bottom (remaining issue number 1): https://github.com/Tundaware/DeckTransition/commit/bdcd27b70a88dd6e6bfcb06562dc614beebb4924

**Comment by HarshilShah** [comment] 2017-07-03 12:33
I just pushed another commit to the branch; the frame needs to be changed in advance for the mask change to work in some cases.

Gonna start work on refactoring out constants soon. Just getting the remaining big issues out of the way before updating for iOS 11/Swift 4, and then working on new features

**Comment by gcox** [comment] 2017-07-03 14:08
@HarshilShah I found another issue with this after pulling it into my own app. My initial VC is only shown briefly, depending on whether an upgrade task needs to be performed prior to showing my real UI. Once it's time to show the real UI, it performs a "Show Detail/Replace" segue to another VC. 

The problem I see with this setup is when the modal has been presented, then the double-height status bar is shown. The presenting VC is shifted down 20px too far, so you don't see it behind the modal. Then, when you dismiss the modal, the VC is still off by 20px, leaving a gap at the top and the bottom off screen by 20px.

I updated the Example app and pushed it to my repo to demonstrate (https://github.com/Tundaware/DeckTransition/tree/status-bar). To clarify:
* Launch App
* Present Modal
* Show double-height status bar (observe that presenting VC is no longer visible)
* Dismiss modal (observe that the presenting VC is shifted down, leaving a gap at the top)

**Comment by HarshilShah** [comment] 2017-07-31 12:04
Would be great if you folks could try the `status-bar` branch now. I think I've finally fixed all the issues

**Comment by hamedh** [comment] 2017-07-31 22:00
I have been running that branch in production for a few weeks now, and it seems there are no issues. Thank you!

**Comment by HarshilShah** [comment] 2017-08-01 00:47
Great! Pushed a big update just yesterday, so let me know if that breaks anything.

Also, if you’re the lib in a production app, would be cool if you could PR the apps using section in the ReadMe

**Comment by HarshilShah** [comment] 2017-08-01 06:23
#21 is now merged to master

**Closed by HarshilShah** 2017-08-01 06:23 UTC

**Comment by gcox** [comment] 2017-08-01 13:34
@HarshilShah Sorry, but this still has a problem. The example I previously provided demonstrates the issue.

I've rebased my example against the updated master branch and added a 20px border to make it more obvious:

https://github.com/Tundaware/DeckTransition/tree/status-bar

**Repro steps**
* Wait for 'loading...' vc to be dismissed and main vc to load.
* Present the modal
* Show the in-call status bar
* Dismiss the in-call status bar
* Dismiss the modal

This is what you're left with:
<img width="487" alt="screenshot 2017-08-01 09 31 19" src="https://user-images.githubusercontent.com/251512/28827722-7189f450-769c-11e7-8e24-f34c5755a189.png">

**Comment by HarshilShah** [comment] 2017-08-01 14:07
Downloaded the project from your link, followed the steps you said, and here's what I'm seeing 
![simulator screen shot 01-aug-2017 7 35 00 pm](https://user-images.githubusercontent.com/3503595/28829248-bcc8f41c-76f0-11e7-892d-57835f41b6a8.png)

**Comment by gcox** [comment] 2017-08-01 14:11
@HarshilShah You are correct, I accidentally listed them in the wrong order, sorry about that. I will update the comment.

**Comment by HarshilShah** [comment] 2017-08-01 14:20
Here's the thing: I printed the frame of the presentingViewController before the transform (this happens right before dismissal) and after the dismissal's completion: The frame is correctly set to be 20px shorter than full height.

So the resizing is happening outside the context of this library, after the dismissal animation.

I removed the LoadingViewController and instead had the transition happen from ViewController class, and that seems to work perfectly. Issue seems to be with presenting the view controller from the loading screen.

**Comment by gcox** [comment] 2017-08-01 19:45
@HarshilShah Thanks for the workaround. That results in an incorrect frame after dismissal, until the large status bar is dismissed, after which it does return to the correct frame.

In addition to this, I see problems during rotation, with both the presenting and the presented view controller frames (even without this workaround applied). 

Given all the problems that seem to stem from using this transition from a VC that was presented by way of a 'replace' segue, I think I'm going to try a different a approach for getting my main VC presented that doesn't cause so many problems.

This all feels like bizarre iOS bugs at this point that aren't worth trying to account for in this library.

**Comment by HarshilShah** [comment] 2017-08-02 02:35
The frame isn’t incorrect, btw, it’s exactly what you’d get if you triggered the double height status bar on just the presenting VC

**Comment by gcox** [comment] 2017-08-02 03:21
Ok, I'll rephrase then:) It *looks* like the frame is wrong since the top of the presenting view is 20px above the bottom of the double-height status bar when this workaround kicks in.

**Comment by HarshilShah** [comment] 2017-08-02 04:49
Workaround isn’t kicking in or doing do anything here, to be clear. That’s stock UIKit behaviour

**Comment by gcox** [comment] 2017-08-02 11:56
I don't think we're on the same page. The workaround *does* kick in, but it fixes one problem by creating a lesser one. The screenshots below show the presenting VC after the following steps:

1. Launch
1. Wait for loading VC to be replaced
1. Present modal
1. Show in-call status bar
1. Dismiss modal

**With workaround**
<img width="487" alt="screenshot 2017-08-02 07 25 49" src="https://user-images.githubusercontent.com/251512/28871880-9a238c7e-7754-11e7-92b1-445508cbcb0b.png">

**Without workaround**
<img width="487" alt="screenshot 2017-08-02 07 26 19" src="https://user-images.githubusercontent.com/251512/28871887-a29efcee-7754-11e7-88ca-40e81f9df1f2.png">

A different workaround is rather than adjusting the origin in the dismiss callback, reduce the size. This makes it look right until the double-height status bar is dismissed, after which a 20px gap is left at the top. To fix the gap at the top, you can reset the frame to the view's window bounds the next time the status bar frame is reduced in height. Of course, as you found yourself, none of this is a problem if I don't present a loading VC, then replace it with the main VC (ViewController.swift). So, it may be better for me just to avoid this scenario with a different design.

**Comment by HarshilShah** [comment] 2017-08-02 12:40
My point was your screenshot labelled "With workaround" is what you'd get if you follow these steps:

1. Launch
2. Wait for loading VC to be replaced
3. Show in-call status bar

That is how UIKit does it. Showing the 40px status bar doesn't shrink the content by 40px, it only shrinks it by 20px

**Comment by gcox** [comment] 2017-08-02 13:30
Ah ok, I understand now. Your workaround does seem to do the trick then:)

What I found in my actual app, which is a bit more complex, was that the view that needed it's origin set to .zero was not actually the presenting VC's view, but the first subview of the furthest ancestor UITransitionView. 

-> UIScreen
--> UIWindow
---> UITransitionView
----> **UIView** - This is the one that needed the origin adjusted
-----> UILayoutContainerView
------> UINavigationTransitionView
-------> UIViewControllerWrapperView
--------> (a few more layers of containers/wrappers/etc)
---------> The presenting VC's view
