### ISSUE TITLE
NavBar Glitch

### ISSUE THREAD

**Issue by sushimatou** [HarshilShah/DeckTransition#28] opened 2017-08-08 18:41 UTC
This glitch appends when the View Controller is not the top-level VC of a Navigation Controller (when you've got a Back Button in the navBar etc.) When the Modal Controller is pushed, the navBar of the previous ViewController is cropped from the top.
![glitch](https://user-images.githubusercontent.com/10923684/29088599-f2e266c6-7c79-11e7-83ab-170b9f551d0c.gif)

**Comment by HarshilShah** [comment] 2017-08-09 07:55
Thanks for the bug and reproduction steps. As soon as I read about this behaviour happening only with a `UINavigationController` with a pushed VC, it all clicked.

Turns out I’d seen this bug before. Apple’s own modal implementation does this exact same thing in iOS 11. I’ve attached a video of the same below. So I’m guessing this is an issue with `UINavigationController` itself, considering the number of new features added.

I’m guessing/hoping Apple fixes this especially seeing it's happening in a major first party app, and I’ll be filing a radar about it too. Don’t think there’s anything I can do about `UINavigationController`’s default behaviour, however.

![2017-08-09 13_24_15](https://user-images.githubusercontent.com/3503595/29110949-140d8f38-7d06-11e7-80cc-b50243603109.gif)

**Comment by HarshilShah** [comment] 2017-08-09 08:27
I've filed [rdar://33794596: UINavigationBar's background shrinks when the visible ViewController presents its own modal](https://openradar.appspot.com/33794596) about this in case anyone wants to dupe

**Comment by hamedh** [comment] 2017-09-01 20:51
Seems like this is fixed on the Apple Music app in the latest iOS 11 beta, but it's not working with DeckTransition. Hmm, maybe there's a workaround on what's happening with the NavBar on iOS 11..

**Comment by Sjoerdjanssenen** [comment] 2017-09-03 12:39
Any updates on this? I'm experiencing this as well. I used to work around this by inserting a `UIView` in the `UINavigationBar` with the solid color of the `UINavigationBar`, but as I'm presenting the modal from a `UISplitViewController` as of now that doesn't work anymore.

**Comment by HarshilShah** [comment] 2017-09-03 13:12
I don't think I can fix this from my side. Radars seem like the only option

**Comment by Sjoerdjanssenen** [comment] 2017-09-04 16:05
I understand, I was wondering if there were any updates on your radars, though.

**Comment by HarshilShah** [comment] 2017-09-04 16:47
Nope, nothing so far. Got marked as a dupe, and the original is still open

**Comment by hamedh** [comment] 2017-09-12 19:28
It's still broken on the GM build too for iOS11, on the Music app too. I wonder if there's a workaround.

**Comment by HarshilShah** [comment] 2017-09-21 04:37
So I figured out the root cause of the bug (safe area insets), and turns out that causes a whole bunch of other bugs as well. #39 addresses this, I'd really appreciate if you could folks could take a look, thanks

**Comment by HarshilShah** [comment] 2017-09-22 19:13
This has been fixed in 1.3.0

**Closed by HarshilShah** 2017-09-22 19:13 UTC
